corpusDir: corpus
testLimit: 50000
seqLen: 100
shrinkLimit: 5000
seed: 0
dictFreq: 0.40
mutConsts: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100, 1000, 10000, 100000, 1000000]
coverage: true
format: text
timeout: 300

# Custom properties for Web3 logic flaws
properties:
  - "echidna_balance_invariant"
  - "echidna_no_unauthorized_transfers"
  - "echidna_reentrancy_guard"
  - "echidna_access_control"
  - "echidna_overflow_underflow"